// Autogenerated from Pigeon (v27.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.therivanta.securepinning.android

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object MessagesPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/**
 * How pinned values in a [PinSet] should be interpreted and compared.
 *
 * This is the wire-format counterpart of the `secure_pinning` package's
 * user-facing `PinningMode` sealed class (deliberately named differently
 * to avoid a same-name collision between the two — this enum is an
 * internal platform-channel detail, not part of the public API most
 * users see).
 *
 * [spki] (Subject Public Key Info hash) is the safe, OWASP-recommended
 * default — it survives certificate renewal as long as the key pair is
 * unchanged. [legacyLeafHash] hashes the whole leaf certificate; it
 * breaks on any renewal, even a same-key one, and exists only for
 * migration compatibility with plugins that pin the full leaf
 * certificate instead of just its public key. [legacyCaHash] pins a
 * CA/root certificate, which effectively trusts *any* certificate that
 * CA issues — a real security footgun. Dart-facing code requires an
 * explicit `acknowledgedRisk` string to select this mode.
 */
enum class WirePinningMode(val raw: Int) {
  SPKI(0),
  LEGACY_LEAF_HASH(1),
  LEGACY_CA_HASH(2);

  companion object {
    fun ofRaw(raw: Int): WirePinningMode? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** The hash algorithm a pin was computed with. */
enum class HashAlgorithm(val raw: Int) {
  /** SHA-256 — the recommended default. */
  SHA256(0),
  /**
   * SHA-1 — supported for compatibility with pins computed by older
   * tooling; prefer [sha256] for new pin sets.
   */
  SHA1(1);

  companion object {
    fun ofRaw(raw: Int): HashAlgorithm? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Which certificate(s) in the chain a pin is checked against.
 *
 * [leafOnly] is the default and the only option supported by
 * secure_pinning's pure-Dart engine (`dart:io` does not expose the full
 * chain). [anyInChain] and [specificIndex] are native-probe-only.
 */
enum class ChainPosition(val raw: Int) {
  LEAF_ONLY(0),
  ANY_IN_CHAIN(1),
  SPECIFIC_INDEX(2);

  companion object {
    fun ofRaw(raw: Int): ChainPosition? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Machine-readable reason a [PinningCheckResult] was not trusted. */
enum class PinningErrorCode(val raw: Int) {
  /**
   * The presented certificate's SPKI hash matched none of the
   * configured pins.
   */
  SPKI_MISMATCH(0),
  /**
   * The presented certificate's whole-certificate hash matched none of
   * the configured pins (legacy leaf-hash mode).
   */
  LEAF_HASH_MISMATCH(1),
  /**
   * No certificate in the chain satisfied the configured pin set
   * (native-probe-only chain positions).
   */
  CHAIN_VALIDATION_FAILED(2),
  /** The certificate's subject does not match the requested hostname. */
  HOSTNAME_MISMATCH(3),
  /** The presented certificate has expired. */
  CERTIFICATE_EXPIRED(4),
  /** The presented certificate is self-signed and not otherwise pinned. */
  SELF_SIGNED_CERTIFICATE(5),
  /**
   * The TLS connection did not establish within the configured connect
   * timeout.
   */
  CONNECT_TIMEOUT(6),
  /** No response arrived within the configured read timeout. */
  READ_TIMEOUT(7),
  /** The device has no network connectivity. */
  NO_INTERNET(8),
  /** The TLS handshake failed for a reason other than a pin mismatch. */
  TLS_HANDSHAKE_FAILURE(9),
  /** The current platform does not support the native probe API. */
  UNSUPPORTED_PLATFORM(10),
  /** The supplied [PinSet] or [PinningCheckRequest] was invalid. */
  INVALID_CONFIGURATION(11),
  /** An error occurred that doesn't map to any other [PinningErrorCode]. */
  UNKNOWN(12);

  companion object {
    fun ofRaw(raw: Int): PinningErrorCode? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Wire-format bundle of the pin values a [PinningCheckRequest] should be
 * validated against, plus how to interpret and compare them.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PinSet (
  /**
   * Pin values as base64 (SPKI) or hex (legacy hash) strings. At least one
   * is required by Dart-side validation; two or more are recommended so a
   * backup pin survives a key/cert rotation.
   */
  val pins: List<String>,
  /** How [pins] should be interpreted and compared. */
  val mode: WirePinningMode,
  /** The hash algorithm [pins] were computed with. */
  val algorithm: HashAlgorithm,
  /** Which certificate(s) in the chain [pins] are checked against. */
  val chainPosition: ChainPosition,
  /** Used only when [chainPosition] is [ChainPosition.specificIndex]. */
  val specificChainIndex: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PinSet {
      val pins = pigeonVar_list[0] as List<String>
      val mode = pigeonVar_list[1] as WirePinningMode
      val algorithm = pigeonVar_list[2] as HashAlgorithm
      val chainPosition = pigeonVar_list[3] as ChainPosition
      val specificChainIndex = pigeonVar_list[4] as Long?
      return PinSet(pins, mode, algorithm, chainPosition, specificChainIndex)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      pins,
      mode,
      algorithm,
      chainPosition,
      specificChainIndex,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PinSet
    return MessagesPigeonUtils.deepEquals(this.pins, other.pins) && MessagesPigeonUtils.deepEquals(this.mode, other.mode) && MessagesPigeonUtils.deepEquals(this.algorithm, other.algorithm) && MessagesPigeonUtils.deepEquals(this.chainPosition, other.chainPosition) && MessagesPigeonUtils.deepEquals(this.specificChainIndex, other.specificChainIndex)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.pins)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.mode)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.algorithm)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.chainPosition)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.specificChainIndex)
    return result
  }
  override fun toString(): String {
    return "PinSet(pins=$pins, mode=$mode, algorithm=$algorithm, chainPosition=$chainPosition, specificChainIndex=$specificChainIndex)"
  }
}

/**
 * A single native probe request — see [SecurePinningHostApi.check].
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PinningCheckRequest (
  /** The URL to probe. */
  val url: String,
  /** The pins to validate the connection against. */
  val pinSet: PinSet,
  /** Extra headers to send with the probe request, if any. */
  val headers: Map<String, String>? = null,
  /** Defaults to GET/HEAD on the native side if omitted. */
  val httpMethod: String? = null,
  /**
   * Maximum time to wait for the TLS connection to establish, in
   * milliseconds.
   */
  val connectTimeoutMs: Long,
  /**
   * Maximum time to wait for a response after the connection is
   * established, in milliseconds.
   */
  val readTimeoutMs: Long,
  /**
   * Reserved for mTLS/client-certificate authentication (planned v1.x).
   * Unused in v0.9 — present now so adding mTLS later is not a schema
   * break.
   */
  val clientCertificate: ByteArray? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PinningCheckRequest {
      val url = pigeonVar_list[0] as String
      val pinSet = pigeonVar_list[1] as PinSet
      val headers = pigeonVar_list[2] as Map<String, String>?
      val httpMethod = pigeonVar_list[3] as String?
      val connectTimeoutMs = pigeonVar_list[4] as Long
      val readTimeoutMs = pigeonVar_list[5] as Long
      val clientCertificate = pigeonVar_list[6] as ByteArray?
      return PinningCheckRequest(url, pinSet, headers, httpMethod, connectTimeoutMs, readTimeoutMs, clientCertificate)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      url,
      pinSet,
      headers,
      httpMethod,
      connectTimeoutMs,
      readTimeoutMs,
      clientCertificate,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PinningCheckRequest
    return MessagesPigeonUtils.deepEquals(this.url, other.url) && MessagesPigeonUtils.deepEquals(this.pinSet, other.pinSet) && MessagesPigeonUtils.deepEquals(this.headers, other.headers) && MessagesPigeonUtils.deepEquals(this.httpMethod, other.httpMethod) && MessagesPigeonUtils.deepEquals(this.connectTimeoutMs, other.connectTimeoutMs) && MessagesPigeonUtils.deepEquals(this.readTimeoutMs, other.readTimeoutMs) && MessagesPigeonUtils.deepEquals(this.clientCertificate, other.clientCertificate)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.url)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.pinSet)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.headers)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.httpMethod)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.connectTimeoutMs)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.readTimeoutMs)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.clientCertificate)
    return result
  }
  override fun toString(): String {
    return "PinningCheckRequest(url=$url, pinSet=$pinSet, headers=$headers, httpMethod=$httpMethod, connectTimeoutMs=$connectTimeoutMs, readTimeoutMs=$readTimeoutMs, clientCertificate=${clientCertificate?.contentToString()})"
  }
}

/**
 * The outcome of a [SecurePinningHostApi.check] call. A pin mismatch is
 * returned as data via [isTrusted]/[errorCode] — it is not thrown as an
 * exception, since it's an expected, frequently-occurring result.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PinningCheckResult (
  /** Whether the connection satisfied the configured pin set. */
  val isTrusted: Boolean,
  /**
   * Non-null when [isTrusted] is false. A pin mismatch is an expected,
   * frequently-occurring *result*, not a thrown exception — see
   * CONTRIBUTING.md.
   */
  val errorCode: PinningErrorCode? = null,
  /** Human-readable, non-sensitive diagnostic detail. */
  val errorDetail: String? = null,
  /** Set on success, for diagnostics/logging. */
  val matchedPinFingerprint: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PinningCheckResult {
      val isTrusted = pigeonVar_list[0] as Boolean
      val errorCode = pigeonVar_list[1] as PinningErrorCode?
      val errorDetail = pigeonVar_list[2] as String?
      val matchedPinFingerprint = pigeonVar_list[3] as String?
      return PinningCheckResult(isTrusted, errorCode, errorDetail, matchedPinFingerprint)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      isTrusted,
      errorCode,
      errorDetail,
      matchedPinFingerprint,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PinningCheckResult
    return MessagesPigeonUtils.deepEquals(this.isTrusted, other.isTrusted) && MessagesPigeonUtils.deepEquals(this.errorCode, other.errorCode) && MessagesPigeonUtils.deepEquals(this.errorDetail, other.errorDetail) && MessagesPigeonUtils.deepEquals(this.matchedPinFingerprint, other.matchedPinFingerprint)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.isTrusted)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.errorCode)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.errorDetail)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.matchedPinFingerprint)
    return result
  }
  override fun toString(): String {
    return "PinningCheckResult(isTrusted=$isTrusted, errorCode=$errorCode, errorDetail=$errorDetail, matchedPinFingerprint=$matchedPinFingerprint)"
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          WirePinningMode.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          HashAlgorithm.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          ChainPosition.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PinningErrorCode.ofRaw(it.toInt())
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PinSet.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PinningCheckRequest.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PinningCheckResult.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is WirePinningMode -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is HashAlgorithm -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is ChainPosition -> {
        stream.write(131)
        writeValue(stream, value.raw.toLong())
      }
      is PinningErrorCode -> {
        stream.write(132)
        writeValue(stream, value.raw.toLong())
      }
      is PinSet -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is PinningCheckRequest -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is PinningCheckResult -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface SecurePinningHostApi {
  /**
   * Validates [request] independently of any specific HTTP request — a
   * standalone probe connection, not a hook into the app's real Dio/http
   * traffic; see the "Core Architectural Insight" section of the project
   * plan for why.
   */
  fun check(request: PinningCheckRequest, callback: (Result<PinningCheckResult>) -> Unit)
  /**
   * Cheap capability probe — true on Android/iOS/macOS; false on
   * Windows/Linux (stubbed) and Web (permanently unsupported). Never
   * throws.
   */
  fun isPlatformSupported(callback: (Result<Boolean>) -> Unit)

  companion object {
    /** The codec used by SecurePinningHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `SecurePinningHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: SecurePinningHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.secure_pinning_platform_interface.SecurePinningHostApi.check$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as PinningCheckRequest
            api.check(requestArg) { result: Result<PinningCheckResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.secure_pinning_platform_interface.SecurePinningHostApi.isPlatformSupported$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.isPlatformSupported{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
