// Autogenerated from Pigeon (v27.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum MessagesPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// How pinned values in a [PinSet] should be interpreted and compared.
///
/// This is the wire-format counterpart of the `secure_pinning` package's
/// user-facing `PinningMode` sealed class (deliberately named differently
/// to avoid a same-name collision between the two — this enum is an
/// internal platform-channel detail, not part of the public API most
/// users see).
///
/// [spki] (Subject Public Key Info hash) is the safe, OWASP-recommended
/// default — it survives certificate renewal as long as the key pair is
/// unchanged. [legacyLeafHash] hashes the whole leaf certificate; it
/// breaks on any renewal, even a same-key one, and exists only for
/// migration compatibility with plugins that pin the full leaf
/// certificate instead of just its public key. [legacyCaHash] pins a
/// CA/root certificate, which effectively trusts *any* certificate that
/// CA issues — a real security footgun. Dart-facing code requires an
/// explicit `acknowledgedRisk` string to select this mode.
enum WirePinningMode: Int, CaseIterable {
  case spki = 0
  case legacyLeafHash = 1
  case legacyCaHash = 2
}

enum HashAlgorithm: Int, CaseIterable {
  case sha256 = 0
  case sha1 = 1
}

/// Which certificate(s) in the chain a pin is checked against.
///
/// [leafOnly] is the default and the only option supported by
/// secure_pinning's pure-Dart engine (`dart:io` does not expose the full
/// chain). [anyInChain] and [specificIndex] are native-probe-only.
enum ChainPosition: Int, CaseIterable {
  case leafOnly = 0
  case anyInChain = 1
  case specificIndex = 2
}

enum PinningErrorCode: Int, CaseIterable {
  case spkiMismatch = 0
  case leafHashMismatch = 1
  case chainValidationFailed = 2
  case hostnameMismatch = 3
  case certificateExpired = 4
  case selfSignedCertificate = 5
  case connectTimeout = 6
  case readTimeout = 7
  case noInternet = 8
  case tlsHandshakeFailure = 9
  case unsupportedPlatform = 10
  case invalidConfiguration = 11
  case unknown = 12
}

/// Generated class from Pigeon that represents data sent in messages.
struct PinSet: Hashable, CustomStringConvertible {
  /// Pin values as base64 (SPKI) or hex (legacy hash) strings. At least one
  /// is required by Dart-side validation; two or more are recommended so a
  /// backup pin survives a key/cert rotation.
  var pins: [String]
  var mode: WirePinningMode
  var algorithm: HashAlgorithm
  var chainPosition: ChainPosition
  /// Used only when [chainPosition] is [ChainPosition.specificIndex].
  var specificChainIndex: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PinSet? {
    let pins = pigeonVar_list[0] as! [String]
    let mode = pigeonVar_list[1] as! WirePinningMode
    let algorithm = pigeonVar_list[2] as! HashAlgorithm
    let chainPosition = pigeonVar_list[3] as! ChainPosition
    let specificChainIndex: Int64? = nilOrValue(pigeonVar_list[4])

    return PinSet(
      pins: pins,
      mode: mode,
      algorithm: algorithm,
      chainPosition: chainPosition,
      specificChainIndex: specificChainIndex
    )
  }
  func toList() -> [Any?] {
    return [
      pins,
      mode,
      algorithm,
      chainPosition,
      specificChainIndex,
    ]
  }
  static func == (lhs: PinSet, rhs: PinSet) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.pins, rhs.pins) && MessagesPigeonInternal.deepEquals(lhs.mode, rhs.mode) && MessagesPigeonInternal.deepEquals(lhs.algorithm, rhs.algorithm) && MessagesPigeonInternal.deepEquals(lhs.chainPosition, rhs.chainPosition) && MessagesPigeonInternal.deepEquals(lhs.specificChainIndex, rhs.specificChainIndex)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PinSet")
    MessagesPigeonInternal.deepHash(value: pins, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: mode, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: algorithm, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: chainPosition, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: specificChainIndex, hasher: &hasher)
  }

  public var description: String {
    return "PinSet(pins: \(String(describing: pins)), mode: \(String(describing: mode)), algorithm: \(String(describing: algorithm)), chainPosition: \(String(describing: chainPosition)), specificChainIndex: \(String(describing: specificChainIndex)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PinningCheckRequest: Hashable, CustomStringConvertible {
  var url: String
  var pinSet: PinSet
  var headers: [String: String]? = nil
  /// Defaults to GET/HEAD on the native side if omitted.
  var httpMethod: String? = nil
  var connectTimeoutMs: Int64
  var readTimeoutMs: Int64
  /// Reserved for mTLS/client-certificate authentication (planned v1.x).
  /// Unused in v0.9 — present now so adding mTLS later is not a schema
  /// break.
  var clientCertificate: FlutterStandardTypedData? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PinningCheckRequest? {
    let url = pigeonVar_list[0] as! String
    let pinSet = pigeonVar_list[1] as! PinSet
    let headers: [String: String]? = nilOrValue(pigeonVar_list[2])
    let httpMethod: String? = nilOrValue(pigeonVar_list[3])
    let connectTimeoutMs = pigeonVar_list[4] as! Int64
    let readTimeoutMs = pigeonVar_list[5] as! Int64
    let clientCertificate: FlutterStandardTypedData? = nilOrValue(pigeonVar_list[6])

    return PinningCheckRequest(
      url: url,
      pinSet: pinSet,
      headers: headers,
      httpMethod: httpMethod,
      connectTimeoutMs: connectTimeoutMs,
      readTimeoutMs: readTimeoutMs,
      clientCertificate: clientCertificate
    )
  }
  func toList() -> [Any?] {
    return [
      url,
      pinSet,
      headers,
      httpMethod,
      connectTimeoutMs,
      readTimeoutMs,
      clientCertificate,
    ]
  }
  static func == (lhs: PinningCheckRequest, rhs: PinningCheckRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.url, rhs.url) && MessagesPigeonInternal.deepEquals(lhs.pinSet, rhs.pinSet) && MessagesPigeonInternal.deepEquals(lhs.headers, rhs.headers) && MessagesPigeonInternal.deepEquals(lhs.httpMethod, rhs.httpMethod) && MessagesPigeonInternal.deepEquals(lhs.connectTimeoutMs, rhs.connectTimeoutMs) && MessagesPigeonInternal.deepEquals(lhs.readTimeoutMs, rhs.readTimeoutMs) && MessagesPigeonInternal.deepEquals(lhs.clientCertificate, rhs.clientCertificate)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PinningCheckRequest")
    MessagesPigeonInternal.deepHash(value: url, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: pinSet, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: headers, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: httpMethod, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: connectTimeoutMs, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: readTimeoutMs, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: clientCertificate, hasher: &hasher)
  }

  public var description: String {
    return "PinningCheckRequest(url: \(String(describing: url)), pinSet: \(String(describing: pinSet)), headers: \(String(describing: headers)), httpMethod: \(String(describing: httpMethod)), connectTimeoutMs: \(String(describing: connectTimeoutMs)), readTimeoutMs: \(String(describing: readTimeoutMs)), clientCertificate: \(String(describing: clientCertificate)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PinningCheckResult: Hashable, CustomStringConvertible {
  var isTrusted: Bool
  /// Non-null when [isTrusted] is false. A pin mismatch is an expected,
  /// frequently-occurring *result*, not a thrown exception — see
  /// CONTRIBUTING.md.
  var errorCode: PinningErrorCode? = nil
  /// Human-readable, non-sensitive diagnostic detail.
  var errorDetail: String? = nil
  /// Set on success, for diagnostics/logging.
  var matchedPinFingerprint: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PinningCheckResult? {
    let isTrusted = pigeonVar_list[0] as! Bool
    let errorCode: PinningErrorCode? = nilOrValue(pigeonVar_list[1])
    let errorDetail: String? = nilOrValue(pigeonVar_list[2])
    let matchedPinFingerprint: String? = nilOrValue(pigeonVar_list[3])

    return PinningCheckResult(
      isTrusted: isTrusted,
      errorCode: errorCode,
      errorDetail: errorDetail,
      matchedPinFingerprint: matchedPinFingerprint
    )
  }
  func toList() -> [Any?] {
    return [
      isTrusted,
      errorCode,
      errorDetail,
      matchedPinFingerprint,
    ]
  }
  static func == (lhs: PinningCheckResult, rhs: PinningCheckResult) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.isTrusted, rhs.isTrusted) && MessagesPigeonInternal.deepEquals(lhs.errorCode, rhs.errorCode) && MessagesPigeonInternal.deepEquals(lhs.errorDetail, rhs.errorDetail) && MessagesPigeonInternal.deepEquals(lhs.matchedPinFingerprint, rhs.matchedPinFingerprint)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PinningCheckResult")
    MessagesPigeonInternal.deepHash(value: isTrusted, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: errorCode, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: errorDetail, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: matchedPinFingerprint, hasher: &hasher)
  }

  public var description: String {
    return "PinningCheckResult(isTrusted: \(String(describing: isTrusted)), errorCode: \(String(describing: errorCode)), errorDetail: \(String(describing: errorDetail)), matchedPinFingerprint: \(String(describing: matchedPinFingerprint)))"
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return WirePinningMode(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return HashAlgorithm(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return ChainPosition(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PinningErrorCode(rawValue: enumResultAsInt)
      }
      return nil
    case 133:
      return PinSet.fromList(self.readValue() as! [Any?])
    case 134:
      return PinningCheckRequest.fromList(self.readValue() as! [Any?])
    case 135:
      return PinningCheckResult.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? WirePinningMode {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? HashAlgorithm {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? ChainPosition {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? PinningErrorCode {
      super.writeByte(132)
      super.writeValue(value.rawValue)
    } else if let value = value as? PinSet {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? PinningCheckRequest {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? PinningCheckResult {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol SecurePinningHostApi {
  /// Validates [request] independently of any specific HTTP request — a
  /// standalone probe connection, not a hook into the app's real Dio/http
  /// traffic; see the "Core Architectural Insight" section of the project
  /// plan for why.
  func check(request: PinningCheckRequest, completion: @escaping (Result<PinningCheckResult, Error>) -> Void)
  /// Cheap capability probe — true on Android/iOS/macOS; false on
  /// Windows/Linux (stubbed) and Web (permanently unsupported). Never
  /// throws.
  func isPlatformSupported(completion: @escaping (Result<Bool, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class SecurePinningHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `SecurePinningHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: SecurePinningHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Validates [request] independently of any specific HTTP request — a
    /// standalone probe connection, not a hook into the app's real Dio/http
    /// traffic; see the "Core Architectural Insight" section of the project
    /// plan for why.
    let checkChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.secure_pinning_platform_interface.SecurePinningHostApi.check\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      checkChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! PinningCheckRequest
        api.check(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      checkChannel.setMessageHandler(nil)
    }
    /// Cheap capability probe — true on Android/iOS/macOS; false on
    /// Windows/Linux (stubbed) and Web (permanently unsupported). Never
    /// throws.
    let isPlatformSupportedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.secure_pinning_platform_interface.SecurePinningHostApi.isPlatformSupported\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isPlatformSupportedChannel.setMessageHandler { _, reply in
        api.isPlatformSupported { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      isPlatformSupportedChannel.setMessageHandler(nil)
    }
  }
}
