// Autogenerated from Pigeon (v27.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


/// How pinned values in a [PinSet] should be interpreted and compared.
///
/// This is the wire-format counterpart of the `secure_pinning` package's
/// user-facing `PinningMode` sealed class (deliberately named differently
/// to avoid a same-name collision between the two — this enum is an
/// internal platform-channel detail, not part of the public API most
/// users see).
///
/// [spki] (Subject Public Key Info hash) is the safe, OWASP-recommended
/// default — it survives certificate renewal as long as the key pair is
/// unchanged. [legacyLeafHash] hashes the whole leaf certificate; it
/// breaks on any renewal, even a same-key one, and exists only for
/// migration compatibility with plugins that pin the full leaf
/// certificate instead of just its public key. [legacyCaHash] pins a
/// CA/root certificate, which effectively trusts *any* certificate that
/// CA issues — a real security footgun. Dart-facing code requires an
/// explicit `acknowledgedRisk` string to select this mode.
enum WirePinningMode {
  spki,
  legacyLeafHash,
  legacyCaHash,
}

enum HashAlgorithm {
  sha256,
  sha1,
}

/// Which certificate(s) in the chain a pin is checked against.
///
/// [leafOnly] is the default and the only option supported by
/// secure_pinning's pure-Dart engine (`dart:io` does not expose the full
/// chain). [anyInChain] and [specificIndex] are native-probe-only.
enum ChainPosition {
  leafOnly,
  anyInChain,
  specificIndex,
}

enum PinningErrorCode {
  spkiMismatch,
  leafHashMismatch,
  chainValidationFailed,
  hostnameMismatch,
  certificateExpired,
  selfSignedCertificate,
  connectTimeout,
  readTimeout,
  noInternet,
  tlsHandshakeFailure,
  unsupportedPlatform,
  invalidConfiguration,
  unknown,
}

class PinSet {
  PinSet({
    required this.pins,
    required this.mode,
    required this.algorithm,
    required this.chainPosition,
    this.specificChainIndex,
  });

  /// Pin values as base64 (SPKI) or hex (legacy hash) strings. At least one
  /// is required by Dart-side validation; two or more are recommended so a
  /// backup pin survives a key/cert rotation.
  List<String> pins;

  WirePinningMode mode;

  HashAlgorithm algorithm;

  ChainPosition chainPosition;

  /// Used only when [chainPosition] is [ChainPosition.specificIndex].
  int? specificChainIndex;

  List<Object?> _toList() {
    return <Object?>[
      pins,
      mode,
      algorithm,
      chainPosition,
      specificChainIndex,
    ];
  }

  Object encode() {
    return _toList();  }

  static PinSet decode(Object result) {
    result as List<Object?>;
    return PinSet(
      pins: (result[0]! as List<Object?>).cast<String>(),
      mode: result[1]! as WirePinningMode,
      algorithm: result[2]! as HashAlgorithm,
      chainPosition: result[3]! as ChainPosition,
      specificChainIndex: result[4] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PinSet || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(pins, other.pins) && _deepEquals(mode, other.mode) && _deepEquals(algorithm, other.algorithm) && _deepEquals(chainPosition, other.chainPosition) && _deepEquals(specificChainIndex, other.specificChainIndex);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PinSet(pins: $pins, mode: $mode, algorithm: $algorithm, chainPosition: $chainPosition, specificChainIndex: $specificChainIndex)';
  }
}

class PinningCheckRequest {
  PinningCheckRequest({
    required this.url,
    required this.pinSet,
    this.headers,
    this.httpMethod,
    required this.connectTimeoutMs,
    required this.readTimeoutMs,
    this.clientCertificate,
  });

  String url;

  PinSet pinSet;

  Map<String, String>? headers;

  /// Defaults to GET/HEAD on the native side if omitted.
  String? httpMethod;

  int connectTimeoutMs;

  int readTimeoutMs;

  /// Reserved for mTLS/client-certificate authentication (planned v1.x).
  /// Unused in v0.9 — present now so adding mTLS later is not a schema
  /// break.
  Uint8List? clientCertificate;

  List<Object?> _toList() {
    return <Object?>[
      url,
      pinSet,
      headers,
      httpMethod,
      connectTimeoutMs,
      readTimeoutMs,
      clientCertificate,
    ];
  }

  Object encode() {
    return _toList();  }

  static PinningCheckRequest decode(Object result) {
    result as List<Object?>;
    return PinningCheckRequest(
      url: result[0]! as String,
      pinSet: result[1]! as PinSet,
      headers: (result[2] as Map<Object?, Object?>?)?.cast<String, String>(),
      httpMethod: result[3] as String?,
      connectTimeoutMs: result[4]! as int,
      readTimeoutMs: result[5]! as int,
      clientCertificate: result[6] as Uint8List?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PinningCheckRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(url, other.url) && _deepEquals(pinSet, other.pinSet) && _deepEquals(headers, other.headers) && _deepEquals(httpMethod, other.httpMethod) && _deepEquals(connectTimeoutMs, other.connectTimeoutMs) && _deepEquals(readTimeoutMs, other.readTimeoutMs) && _deepEquals(clientCertificate, other.clientCertificate);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PinningCheckRequest(url: $url, pinSet: $pinSet, headers: $headers, httpMethod: $httpMethod, connectTimeoutMs: $connectTimeoutMs, readTimeoutMs: $readTimeoutMs, clientCertificate: $clientCertificate)';
  }
}

class PinningCheckResult {
  PinningCheckResult({
    required this.isTrusted,
    this.errorCode,
    this.errorDetail,
    this.matchedPinFingerprint,
  });

  bool isTrusted;

  /// Non-null when [isTrusted] is false. A pin mismatch is an expected,
  /// frequently-occurring *result*, not a thrown exception — see
  /// CONTRIBUTING.md.
  PinningErrorCode? errorCode;

  /// Human-readable, non-sensitive diagnostic detail.
  String? errorDetail;

  /// Set on success, for diagnostics/logging.
  String? matchedPinFingerprint;

  List<Object?> _toList() {
    return <Object?>[
      isTrusted,
      errorCode,
      errorDetail,
      matchedPinFingerprint,
    ];
  }

  Object encode() {
    return _toList();  }

  static PinningCheckResult decode(Object result) {
    result as List<Object?>;
    return PinningCheckResult(
      isTrusted: result[0]! as bool,
      errorCode: result[1] as PinningErrorCode?,
      errorDetail: result[2] as String?,
      matchedPinFingerprint: result[3] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PinningCheckResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(isTrusted, other.isTrusted) && _deepEquals(errorCode, other.errorCode) && _deepEquals(errorDetail, other.errorDetail) && _deepEquals(matchedPinFingerprint, other.matchedPinFingerprint);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PinningCheckResult(isTrusted: $isTrusted, errorCode: $errorCode, errorDetail: $errorDetail, matchedPinFingerprint: $matchedPinFingerprint)';
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is WirePinningMode) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is HashAlgorithm) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is ChainPosition) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    }    else if (value is PinningErrorCode) {
      buffer.putUint8(132);
      writeValue(buffer, value.index);
    }    else if (value is PinSet) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is PinningCheckRequest) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    }    else if (value is PinningCheckResult) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : WirePinningMode.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : HashAlgorithm.values[value];
      case 131:
        final value = readValue(buffer) as int?;
        return value == null ? null : ChainPosition.values[value];
      case 132:
        final value = readValue(buffer) as int?;
        return value == null ? null : PinningErrorCode.values[value];
      case 133:
        return PinSet.decode(readValue(buffer)!);
      case 134:
        return PinningCheckRequest.decode(readValue(buffer)!);
      case 135:
        return PinningCheckResult.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class SecurePinningHostApi {
  /// Constructor for [SecurePinningHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  SecurePinningHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Validates [request] independently of any specific HTTP request — a
  /// standalone probe connection, not a hook into the app's real Dio/http
  /// traffic; see the "Core Architectural Insight" section of the project
  /// plan for why.
  Future<PinningCheckResult> check(PinningCheckRequest request) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.secure_pinning_platform_interface.SecurePinningHostApi.check$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as PinningCheckResult;
  }

  /// Cheap capability probe — true on Android/iOS/macOS; false on
  /// Windows/Linux (stubbed) and Web (permanently unsupported). Never
  /// throws.
  Future<bool> isPlatformSupported() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.secure_pinning_platform_interface.SecurePinningHostApi.isPlatformSupported$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }
}
